name: AddMilestone
on:
  issues:
    types: [opened,edited]

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: guguducken/milestone-add-action@v0.0.1
        with:
          action-token: ${{ secrets.ACTION_TOKEN }}
          co-milestones: >
            {
              "[BUG]":"v0.0.1",
              "[MOC FEATURE]":"v0.0.1"
            }