name: Build
on:
  push:
    branches:
      - "feature/**"

jobs:
  GetAwsValue:
    uses: ./.github/workflows/GetAwsValue.yml
    with:
      environment: DEV
      # DEV환경은 [ap-northeast-2] 로 고정
      region: ap-northeast-2

  Build:
    runs-on: ubuntu-latest
    needs: GetAwsValue
    steps:
      - name: Checkout
          uses: actions/checkout@v3

      - name: Build Test
          id: build-image
          env:
            ECR_REGISTRY: ${{ needs.GetAwsValue.outputs.registry }}
            ECR_REPOSITORY: ${{ needs.GetAwsValue.outputs.repository }}
            IMAGE_TAG: ${{ github.sha }}
          run: |
            echo ECR_REGISTRY= $ECR_REGISTRY
            echo ECR_REPOSITORY = $ECR_REPOSITORY
