name: Build
on:
  push:
    branches:
      - "feature/**"

jobs:
  GetAwsValue:
    uses: ./.github/workflows/GetAwsValue.yml
    with:
      # DEV환경은 [ap-northeast-2] 로 고정
      environment: DEV
      region: ap-northeast-2

  Build:
    runs-on: ubuntu-latest
    needs: GetAwsValue
    steps:
      - name: Build Test
        env:
          ECR_REGISTRY: ${{ needs.GetAwsValue.outputs.registry }}
          ECR_REPOSITORY: ${{ needs.GetAwsValue.outputs.repository }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo ECR_REGISTRY= $ECR_REGISTRY
          echo ECR_REPOSITORY = $ECR_REPOSITORY
