name: CreateIssuesFromTodos

on:
  push:
    branches:
      - "release/**"

jobs:
  CreateIssuesFromTodos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: todocheck-bot
        uses: bengsparks/todocheck-bot@v0.0.2
