name: CreateIssuesFromTodos

on:
  push:
    branches:
      - "develop"

jobs:
  CreateIssuesFromTodos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: todo-actions
        uses: KyeongminKang-GGQ/todo-actions@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TODO_ACTIONS_MONGO_URL: ${{ secrets.TODO_ACTIONS_MONGO_URL }}
