name: DeployToDev

# develop 브랜치에 commit이 push 되면 자동으로 DEV 환경으로 배포된다.
# develop 브랜치에 push된 commit으로 배포

env:
  # DEV환경은 [ap-northeast-2] 로 고정
  region: ap-northeast-2
  environment: DEV

on:
  push:
    branches:
      - "develop**"

jobs:
  GetAwsValue:
    uses: ./.github/workflows/GetAwsValue.yml
    with:
      environment: ${{ env.environment }}
      region: ${{ env.region }}

  BuildAndDeployToDev:
    uses: ./.github/workflows/Deploy.yml
    needs: GetAwsValue
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
    with:
      region: ${{ env.region }}
      commit: ${{ github.sha }}
      registry: ${{ needs.GetAwsValue.outputs.registry }}
      repository: ${{ needs.GetAwsValue.outputs.repository }}
      taskDefinition: ${{ needs.GetAwsValue.outputs.taskDefinition }}
      container: ${{ needs.GetAwsValue.outputs.container }}
      service: ${{ needs.GetAwsValue.outputs.service }}
      cluster: ${{ needs.GetAwsValue.outputs.cluster }}
