name: Deploy

# AWS 배포를 위한 Workflow
# Deploy Workflow는 다른 Workflow 에서 호출한다
# Deploy Workflow 호출 시 secrets 값과 inputs 값을 넘겨주어야 한다.

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
    inputs:
      region:
        type: string
        required: true
      commit:
        type: string
        required: true
      registry:
        type: string
        required: true
      repository:
        type: string
        required: true
      taskDefinition:
        type: string
        required: true
      container:
        type: string
        required: true
      service:
        type: string
        required: true
      cluster:
        type: string
        required: true

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print information
        run: |
          echo ECR_REGISTRY = ${{ inputs.registry }}
          echo ECR_REPOSITORY = ${{ inputs.repository }}
          echo task_definition = ${{ inputs.taskDefinition }}
          echo container = ${{ inputs.container }}
          echo service = ${{ inputs.service }}
          echo cluster = ${{ inputs.cluster }}
          echo ${{ github.sha }} / ${{ inputs.commit }}