name: ExtractVersion

on:
  workflow_call:
    outputs:
      version:
        description: "Extract version name"
        value: ${{ jobs.ExtractVersion.outputs.version }}

jobs:
  ExtractVersion:
    if: ${{ startsWith(github.ref_name, 'release/') || startsWith(github.ref_name, 'hotfix/') }}
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version_name.outputs.version }}
    steps:
      - name: Start SetTagForProd Workflow
        run: |
          echo Start SetTagForProd Workflow

      - uses: actions/checkout@v2
      - name: Extract Version Name
        run: |
          if '${{ startsWith(github.ref_name, 'hotfix/') }}'
          then
            if '${{ inputs.identifier != '' }}
            then
              echo "::set-output name=version::$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')-${{ inputs.identifier }}+hotfix.$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{6}')"
            else
              echo "::set-output name=version::$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')+hotfix.$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{6}')"
            fi
          elif '${{ startsWith(github.ref_name, 'release/') }}'
          then
            if '${{ inputs.identifier != '' }}
            then
              echo "::set-output name=version::$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\+[0-9]{6}')"
            else
              echo "::set-output name=version::$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')-${{ inputs.identifier }}$(echo '${{ github.ref_name }}' | egrep -o '\+[0-9]{6}')"
            fi
          else
            echo ""
          fi
        id: extract_version_name

      - name: Print Version
        run: |
          echo ${{ steps.extract_version_name.outputs.version }}