name: GetAwsValueCaller

# AWS 배포를 위해 필요한 값을 구하는 Workflow
# 개발자는 아래 env 값을 확인하고 필요 시 수정해주어야 한다.
env:
  service_prefix: ecss
  cluster_prefix: ecsc
  container_name: lol_auth
  product_name: ggq
  repository_prefix: ecr
  account_id_dev: 118166980108
  account_id_stg: 666644083535
  account_id_prod: 71637104407

on:
  workflow_dispatch:
    inputs:
      region:
        type: string
        required: true
        description: Server region full name (ex. ap-northeast-2)
      environment:
        type: string
        required: true
        description: Server environment (DEV, STG, PROD)

jobs:
  GetAwsValueCaller:
    uses: ./.github/workflows/GetAwsValue.yml
    with:
      environment: ${{ inputs.environment }}
      region: ${{ inputs.region }}

  PrintInformation:
    runs-on: ubuntu-latest
    needs: GetAwsValueCaller
    steps:
      - name: Print information
        run: |
          echo ECR_REGISTRY = ${{ needs.GetAwsValueCaller.outputs.registry }}
          echo ECR_REPOSITORY = ${{ needs.GetAwsValueCaller.outputs.repository }}
          echo task_definition = ${{ needs.GetAwsValueCaller.outputs.taskDefinition }}
          echo container = ${{ needs.GetAwsValueCaller.outputs.container }}
          echo service = ${{ needs.GetAwsValueCaller.outputs.service }}
          echo cluster = ${{ needs.GetAwsValueCaller.outputs.cluster }}
