name: GetCommitFromTag
on:
  workflow_call:
    outputs:
      commit:
        value: ${{ jobs.GetCommitFromTag.outputs.commit }}
    inputs:
      tag:
        type: string
        required: true

jobs:
  GetCommitFromTag:
    runs-on: ubuntu-latest
    outputs:
      commit: ${{ steps.get_commit.outputs.commit }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get commit
        id: get_commit
        run: |
          echo "::set-output name=commit::$(git rev-list ${{ inputs.tag }})"

      - name: Print commit
        run: |
          echo ${{ inputs.tag }} :: ${{ steps.get_commit.outputs.commit }}
