name: GetLatestTag
on:
  workflow_call:
    outputs:
      tag:
        value: ${{ jobs.GetLatestTag.outputs.tag }}
    inputs:
      environment:
        type: string
        required: true

jobs:
  GetLatestTag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.extract_latest_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Print values
        run: |
          echo environment = ${{ inputs.environment }} / branch = ${{ github.ref_name }} / current_tag = $(git describe --tag)

      - name: Get latest tag
        id: extract_latest_tag
        run: |
          if '${{ inputs.environment == 'PROD' && github.ref_name == 'main' }}'
          then
            echo "::set-output name=tag::$(git describe --tag)"
          elif '${{ inputs.environment == 'STG' && (startsWith(github.ref_name, 'hotfix/') || startsWith(github.ref_name, 'release/')) }}'
          then
            echo "::set-output name=tag::$(git describe --match "$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')-rc*" --abbrev=0 --tags $(git rev-list --tags --max-count=1))"
          else
            echo ""
          fi

      - name: Print latest tag
        run: |
          echo ${{ steps.extract_latest_tag.outputs.tag }}
