name: GetShortRegionName
on:
  workflow_dispatch:
    inputs:
      region:
        type: string
        required: true
        description: 배포할 Region 이름
      envrionment:
        type: string
        required: true
        description: 배포할 환경

jobs:
  GetShortRegionName:
    if: ${{ inputs.region != '' && inputs.envrionment != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: 버전 정보 프린트
        id: extract_name
        run: |
          echo ${{ inputs.environment }} | tr '[A-Z]' '[a-z]'
          echo $(echo "${{ inputs.region }}'" | sed -rn 's/([^[[:digit:]])[^[[:digit:]]+\-([^[[:digit:]])[^[[:digit:]]+\-([[:digit:]])/\1\2\3/p')
          echo "::set-output name=name::task-definition-${${{ inputs.environment }},,}-$(echo "${{ inputs.region }}'" | sed -rn 's/([^[[:digit:]])[^[[:digit:]]+\-([^[[:digit:]])[^[[:digit:]]+\-([[:digit:]])/\1\2\3/p')"

      - name: 버전 정보 프린트
        run: |
          echo ${{ steps.extract_name.outputs.name }}