name: Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true
      identifier:
        type: string
        required: false


jobs:
  BuildAndDeployToStg:
    if: ${{ inputs.environment }} == 'STG' && ${{ github.ref_name }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 식별자가 있는 경우 (STG, RC)
        - if: ${{ inputs.identifer != '' }}
        - run: echo "##[set-output name=version;]$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}.${{ inputs.identifier }}')"
          id: extract_version_name

      - name: 식별자가 없는 경우 (PRD, 정식버전)
        - run: echo "##[set-output name=version;]$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
          id: extract_version_name
      - name: 태깅
        - tag_name: ${{ steps.extract_version_name.outputs.version }}
      - name: Print Version
        run: |
          echo ${{ steps.extract_version_name.outputs.version }}

  BuildAndDeployToPrd:
    if: ${{ inputs.environment }} == 'PRD' && ${{ github.ref_name }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 버전 정보 추출
        run: echo "##[set-output name=version;]$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
        id: extract_version_name
        with:
          tag_name: ${{ steps.extract_version_name.outputs.version }}
          release_name: ${{ steps.extract_version_name.outputs.version }}
      - name: Print Version
        run: |
          echo ${{ steps.extract_version_name.outputs.version }}