name: ManualDeployToProd
on:
  workflow_dispatch:
    inputs:
      region:
        type: choice
        required: true
        description: 배포할 AWS region를 선택하세요.
        options:
          - eu-west-1
          - ap-northeast-2

jobs:
  GetLatestTag:
    if: ${{ github.ref_name == 'main' }}
    uses: ./.github/workflows/GetLatestTag.yml
    with:
      environment: PROD

  GetCommitFromTag:
    if: ${{ github.ref_name == 'main' }}
    uses: ./.github/workflows/GetCommitFromTag.yml
    needs: GetLatestTag
    with:
      tag: ${{ needs.GetLatestTag.outputs.tag }}

  BuildAndDeployToProd:
    if: ${{ github.ref_name == 'main' }}
    needs: GetCommitFromTag
    uses: ./.github/workflows/Deploy.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID_PROD }}
    with:
      region: ${{ inputs.region }}
      commit: ${{ needs.GetCommitFromTag.outputs.commit }}
      environment: PROD

  NotifyToSlackToSuccess:
    if: ${{ success() }}
    needs: [GetLatestTag, GetCommitFromTag, BuildAndDeployToProd]
    uses: ./.github/workflows/NotifyToSlack.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      environment: PROD
      version: ${{ needs.GetLatestTag.outputs.tag }}
      status: success
      region: ${{ inputs.region }}
      commit: ${{ needs.GetCommitFromTag.outputs.commit }}

  NotifyToSlackToFail:
    if: ${{ failure() }}
    needs: [GetLatestTag, GetCommitFromTag, BuildAndDeployToProd]
    uses: ./.github/workflows/NotifyToSlack.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      environment: PROD
      version: ${{ needs.GetLatestTag.outputs.tag }}
      status: failure
      region: ${{ inputs.region }}
      commit: ${{ needs.GetCommitFromTag.outputs.commit }}