name: ManualDeployToStg
on:
  workflow_dispatch:
    inputs:
      identifier:
        type: string
        required: false
      region:
        type: choice
        description: AWS region
        options:
          - eu-west-1
          - ap-northeast-2
      tagging:
        type: boolean
        description: Auto tagging / 모든 region 배포 완료 후 버전 태깅 시 꼭 체크해주세요!

jobs:
  ExtractVersion:
    uses: ./.github/workflows/ExtractVersion.yml

  SetTagForStg:
    if: ${{ inputs.tagging }}
    uses: ./.github/workflows/SetTagForStg.yml
    needs: ExtractVersion
    with:
      identifier: ${{ inputs.identifier }}
      version: ${{ needs.ExtractVersion.outputs.version }}

  Test:
    runs-on: ubuntu-latest
    needs: SetTagForStg
    steps:
      - run: |
          echo ${{ needs.SetTagForStg.result }}

  BuildAndDeployToStg:
    if: ${{ inputs.identifier != '' && (needs.SetTagForStg.result == 'skipped' || startsWith(github.ref_name, 'release/') || inputs.identifier != '' && startsWith(github.ref_name, 'hotfix/')) }}
    needs: SetTagForStg
    uses: ./.github/workflows/ManualDeploy.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STG }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STG }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY_STG }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_STG }}
    with:
      taskDefinition: task-definition-stg.json
      # Reusable workflow에서 env를 공유할 수 없음
      # TODO: STG 서버 설정 후 변경 예정
      container: lol_auth
      cluster: ecsc-an2-d-ggq
      service_prefix: ecss-an2-d-ggq
      region: ${{ inputs.region }}

  NotifySlackToSuccess:
    if: ${{ success() }}
    needs: [ExtractVersion, BuildAndDeployToStg]
    uses: ./.github/workflows/NotifySlack.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      environment: STG
      version: ${{ needs.ExtractVersion.outputs.version }}
      status: success
      region: ${{ inputs.region }}

  NotifySlackToFail:
    if: ${{ failure() }}
    needs: [ExtractVersion, BuildAndDeployToStg]
    uses: ./.github/workflows/NotifySlack.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      environment: STG
      version: ${{ needs.ExtractVersion.outputs.version }}
      status: failure
      region: ${{ inputs.region }}