name: ManualDeployToStg
on:
  workflow_dispatch:
    inputs:
      identifier:
        type: string
        required: false

jobs:
  SetTagForStg:
    uses: ./.github/workflows/SetTagForStg.yml
    with:
      identifier: ${{ inputs.identifier }}

  BuildAndDeployToStg:
    if: ${{ inputs.identifier != '' && (startsWith(github.ref_name, 'release/') || inputs.identifier != '' && startsWith(github.ref_name, 'hotfix/')) }}
    needs: SetTagForStg
    uses: ./.github/workflows/ManualDeploy.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STG }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STG }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY_STG }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_STG }}
    with:
      taskDefinition: task-definition-stg.json
      # Reusable workflow에서 env를 공유할 수 없음
      # TODO: STG 서버 설정 후 변경 예정
      container: lol_auth
      cluster: ecsc-an2-d-ggq
      service_prefix: ecss-an2-d-ggq

  NotifySlackToSuccess:
    if: ${{ success() }}
    needs: [SetTagForStg, BuildAndDeployToStg]
    uses: ./.github/workflows/NotifySlack.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      environment: STG
      version: ${{ needs.SetTagForStg.outputs.version }}
      status: success

  NotifySlackToFail:
    if: ${{ failure() }}
    needs: [SetTagForStg, BuildAndDeployToStg]
    uses: ./.github/workflows/NotifySlack.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      environment: STG
      version: ${{ needs.SetTagForStg.outputs.version }}
      status: failure