name: ManualDeployToDev
on:
  workflow_dispatch:
    inputs:
      region:
        type: choice
        required: true
        description: AWS region
        options:
          - ap-northeast-2

jobs:
  BuildAndDeployToDev:
    if: ${{ startsWith(github.ref_name, 'feature/') }}
    uses: ./.github/workflows/Deploy.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY_DEV }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_DEV }}
    with:
      # Reusable workflow에서 env를 공유할 수 없음
      # TODO: STG 서버 설정 후 변경 예정
      container: lol_auth
      cluster: ecsc-an2-d-ggq
      service_prefix: ecss-an2-d-ggq
      region: ${{ inputs.region }}
      commit: ${{ github.sha }}
      environment: DEV