name: ManualDeployToProd
on:
  workflow_dispatch:
    inputs:
      region:
        type: choice
        description: 배포할 AWS region를 선택하세요.
        options:
          - eu-west-1
          - ap-northeast-2

jobs:
  GetLatestTag:
    uses: ./.github/workflows/GetLatestTag.yml
    with:
      environment: PROD

  GetCommitFromTag:
    runs-on: ubuntu-latest
    needs: GetLatestTag
    outputs:
      tag: ${{ steps.extract_latest_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get commit
        id: get_commit
        run: |
          echo "::set-output name=commit::$(git rev-list ${{ needs.GetLatestTag.outputs.tag }})"

      - name: Print commit
        run: |
          echo ${{ steps.get_commit.outputs.commit }}

  BuildAndDeployToProd:
    if: ${{ github.ref_name == 'main' }}
    needs: GetCommitFromTag
    uses: ./.github/workflows/Deploy.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY_PROD }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_PROD }}
    with:
      taskDefinition: task-definition-prod.json
      # Reusable workflow에서 env를 공유할 수 없음
      # TODO: STG 서버 설정 후 변경 예정
      container: lol_auth
      cluster: ecsc-an2-d-ggq
      service_prefix: ecss-an2-d-ggq
      region: ${{ inputs.region }}
      commit: ${{ needs.GetCommitFromTag.outputs.commit }}

  NotifySlackToSuccess:
    if: ${{ success() }}
    needs: [GetCommitFromTag, BuildAndDeployToProd]
    uses: ./.github/workflows/NotifySlack.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      environment: PROD
      version: ${{ needs.GetLatestTag.outputs.tag }}
      status: success
      region: ${{ inputs.region }}
      commit: ${{ needs.GetCommitFromTag.outputs.commit }}

  NotifySlackToFail:
    if: ${{ failure() }}
    needs: [GetCommitFromTag, BuildAndDeployToProd]
    uses: ./.github/workflows/NotifySlack.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      environment: PROD
      version: ${{ needs.GetLatestTag.outputs.tag }}
      status: failure
      region: ${{ inputs.region }}
      commit: ${{ needs.GetCommitFromTag.outputs.commit }}