name: ManualDeployToStg
on:
  workflow_dispatch:
    inputs:
      identifier:
        type: string
        required: false

jobs:
  CreateTagForRelease:
    if: ${{ inputs.identifier != '' && startsWith(github.ref_name, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # 실제로 서버 배포하는 Action 추가
      # 슬랙 배포 알람 Action 추가

      - name: 버전 정보 추출
        run: |
          echo "::set-output name=version::$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')-${{ inputs.identifier }}$(echo '${{ github.ref_name }}' | egrep -o '\+[0-9]{6}')"
        id: extract_version_name
      - name: Print Tag
        run: |
          echo ${{ steps.extract_version_name.outputs.version }}
      - if: ${{ steps.extract_version_name.outputs.version != '' }}
        name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.extract_version_name.outputs.version }}

  BuildAndDeployToStgAtReleaseBranch:
    if: ${{ inputs.identifier != '' && startsWith(github.ref_name, 'release/') }}
    needs: CreateTagForRelease

    runs-on: ubuntu-latest

    steps:
      # 실제로 서버 배포하는 Action 추가
      - name: 서버 배포
        run: |
          echo Release Server

      - name: 버전 정보 추출
        run: |
          echo "::set-output name=version::$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')-${{ inputs.identifier }}$(echo '${{ github.ref_name }}' | egrep -o '\+[0-9]{6}')"
        id: extract_version_name
      - name: 버전 정보 프린트
        run: |
          echo ${{ steps.extract_version_name.outputs.version }}

  NotifySlack:
    if: ${{ inputs.identifier != '' && startsWith(github.ref_name, 'release/') && (needs.CreateTagForRelease.result == 'failure' || always()) }}
    needs: [CreateTagForRelease, BuildAndDeployToStgAtReleaseBranch]

    runs-on: ubuntu-latest
    steps:
      - name: Send slack
        uses: ./.github/workflows/NotifySlack.yml
        with:
          environment: "STG"
          version: ${{ steps.extract_version_name.outputs.version }}

  CreateTagForHotfix:
    if: ${{ inputs.identifier != '' && startsWith(github.ref_name, 'hotfix/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # 실제로 서버 배포하는 Action 추가
      # 슬랙 배포 알람 Action 추가

      - name: 버전 정보 추출
        run: |
          echo "::set-output name=version::$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')-${{ inputs.identifier }}+hotfix.$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{6}')"
        id: extract_version_name
      - name: Print Tag
        run: |
          echo ${{ steps.extract_version_name.outputs.version }}
      - if: ${{ steps.extract_version_name.outputs.version != '' }}
        name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.extract_version_name.outputs.version }}

      - name: Send slack if failed
        if: ${{ failure() }}
        run: |
          echo "Build Fail"


  BuildAndDeployToStgAtHotfixBranch:
    if: ${{ inputs.identifier != '' && startsWith(github.ref_name, 'hotfix/') }}
    needs: CreateTagForHotfix

    runs-on: ubuntu-latest

    steps:
      # 실제로 서버 배포하는 Action 추가
      - name: 서버 배포
        run: |
          echo Release Server

      # 슬랙 배포 알람 Action 추가
      - name: Send slack if failed
        if: ${{ failure() }}
        run: |
          echo "Build Fail"

      - name: Send slack if completed
        if: ${{ success() }}
        run: |
          echo "Build Success"
