name: ManualDeployToProd
on:
  workflow_dispatch:
    inputs:
      region:
        type: choice
        description: AWS region
        options:
          - eu-west-1
          - ap-northeast-2

# Reusable workflow에서 env를 공유할 수 없음
# PROD 서버 설정 후 변경
env:
  service_prefix: ecss-an2-d-ggq
  cluster: ecsc-an2-d-ggq
  container: lol_auth

jobs:
  BuildAndDeployToProd:
    if: ${{ startsWith(github.ref_name, 'release/') || startsWith(github.ref_name, 'hotfix/') }}
    uses: ./.github/workflows/ManualDeploy.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY_PROD }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_PROD }}
    with:
      taskDefinition: task-definition-prod.json
      # Reusable workflow에서 env를 공유할 수 없음
      # TODO: STG 서버 설정 후 변경 예정
      container: lol_auth
      cluster: ecsc-an2-d-ggq
      service_prefix: ecss-an2-d-ggq
      region: ${{ inputs.region }}

  SetTagForProd:
    needs: BuildAndDeployToProd
    uses: ./.github/workflows/SetTagForProd.yml

  NotifySlackToSuccess:
    if: ${{ success() }}
    needs: SetTagForProd
    uses: ./.github/workflows/NotifySlack.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      environment: PROD
      version: ${{ needs.SetTagForProd.outputs.version }}
      status: success

  NotifySlackToFail:
    if: ${{ failure() }}
    needs: SetTagForProd
    uses: ./.github/workflows/NotifySlack.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      environment: PROD
      version: ${{ needs.SetTagForProd.outputs.version }}
      status: failure