name: ManualDeployToPrd
on:
  workflow_dispatch:

jobs:
  BuildAndDeployToPrd:
    if: ${{ startsWith(github.ref_name, 'release/') || startsWith(github.ref_name, 'hotfix/') }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 버전 정보 추출
        run: |
          echo "::set-output name=version::$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\+[0-9]{6}')"
        id: extract_version_name
      - name: Print Tag
        run: |
          echo ${{ steps.extract_version_name.outputs.version }}

      - name: Set Git config
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "Github Actions"

      - name: Merge to main
        run: |
            git fetch --unshallow
            git checkout main
            git pull
            git merge --no-ff ${{ github.ref_name }} -m "Auto-merge from ${{ github.ref_name }} to master"
            git push

      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branches: ${{ github.ref_name }}

  ReleaseAndTag:
    if: ${{ startsWith(github.ref_name, 'release/') || startsWith(github.ref_name, 'hotfix/') }}
    needs: BuildAndDeployToPrd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - run: |
          echo  ${{ github.ref_name }}.${{ github.sha }}
          
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.4

      - name: Running on the default branch.
        if: steps.branch-name.outputs.is_default == 'true'
        run: |
          echo "Running on default: ${{ steps.branch-name.outputs.current_branch }}"
          
      - name: Running on a pull request branch.
        if: steps.branch-name.outputs.is_default == 'false'
        run: |
          echo "Running on pr: ${{ steps.branch-name.outputs.current_branch }}"
          
      - name: Running on a pull request branch. head_ref_branch
        if: steps.branch-name.outputs.is_default == 'false'
        run: |
          echo "head_ref_branch on pr: ${{ steps.branch-name.outputs.head_ref_branch }}"

      - name: 정보 추출
        run: |
          echo  ${{ github.ref_name }}.${{ github.sha }}
      - name: 버전 정보 추출
        run: |
          echo "::set-output name=version::$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\+[0-9]{6}')"
        id: extract_version_name
      - name: Print Tag
        run: |
          echo ${{ steps.extract_version_name.outputs.version }}

      - name: Release 생성
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version_name.outputs.version }}
          release_name: ${{ steps.extract_version_name.outputs.version }}
