name: ManualDeployToStg

# release/hotfix 브랜치에서 가장 최근의 rc 버전 TAG로 AWS 배포 하는 Workflow
# BuildAndDeployToStg job에서 container, cluster, service_prefix 를 변경하여 사용하도록 한다.

on:
  workflow_dispatch:
    environment:
      type: choice
      required: true
      description: 배포 환경 (수정 불가)
      options:
        - STG
    inputs:
      region:
        type: choice
        required: true
        description: 배포할 AWS region를 선택하세요.
        options:
          - eu-west-1
          - ap-northeast-2

jobs:
  # release/hotfix 브랜치에서 발행된 최신의 rc 태깅을 찾는다.
  GetLatestTag:
    if: ${{ startsWith(github.ref_name, 'release/') || startsWith(github.ref_name, 'hotfix/') }}
    uses: ./.github/workflows/GetLatestTag.yml
    with:
      environment: ${{ inputs.environment }}

  # tag이름으로 배포할 commit 확인
  GetCommitFromTag:
    if: ${{ startsWith(github.ref_name, 'release/') || startsWith(github.ref_name, 'hotfix/') }}
    uses: ./.github/workflows/GetCommitFromTag.yml
    needs: GetLatestTag
    with:
      tag: ${{ needs.GetLatestTag.outputs.tag }}

  # 배포 시 필요한 값 가져오기
  GetAwsValue:
    uses: ./.github/workflows/GetAwsValue.yml
    with:
      environment: ${{ inputs.environment }}
      region: ${{ inputs.region }}

  # commit id로 STG 배포
  BuildAndDeployToStg:
    if: ${{ startsWith(github.ref_name, 'release/') || startsWith(github.ref_name, 'hotfix/') }}
    needs: [GetCommitFromTag, GetAwsValue]
    uses: ./.github/workflows/Deploy.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STG }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STG }}
    with:
      region: ${{ inputs.region }}
      commit: ${{ needs.GetCommitFromTag.outputs.commit }}
      registry: ${{ needs.GetAwsValue.outputs.registry }}
      repository: ${{ needs.GetAwsValue.outputs.repository }}
      taskDefinition: ${{ needs.GetAwsValue.outputs.taskDefinition }}
      container: ${{ needs.GetAwsValue.outputs.container }}
      service: ${{ needs.GetAwsValue.outputs.service }}
      cluster: ${{ needs.GetAwsValue.outputs.cluster }}

  NotifyToSlackToSuccess:
    if: ${{ success() }}
    needs: [GetLatestTag, GetCommitFromTag, BuildAndDeployToStg]
    uses: ./.github/workflows/NotifyToSlack.yml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      version: ${{ needs.GetLatestTag.outputs.tag }}
      status: success
      region: ${{ inputs.region }}
      commit: ${{ needs.GetCommitFromTag.outputs.commit }}

  NotifyToSlackToFail:
    if: ${{ failure() }}
    needs: [GetLatestTag, GetCommitFromTag, BuildAndDeployToStg]
    uses: ./.github/workflows/NotifyToSlack.yml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      version: ${{ needs.GetLatestTag.outputs.tag }}
      status: failure
      region: ${{ inputs.region }}
      commit: ${{ needs.GetCommitFromTag.outputs.commit }}
