name: ManualDeployToStg
on:
  workflow_dispatch:
    inputs:
      region:
        type: choice
        required: true
        description: 배포할 AWS region를 선택하세요.
        options:
          - eu-west-1
          - ap-northeast-2

jobs:
  GetLatestTag:
    if: ${{ startsWith(github.ref_name, 'release/') || startsWith(github.ref_name, 'hotfix/') }}
    uses: ./.github/workflows/GetLatestTag.yml
    with:
      environment: STG

  GetCommitFromTag:
    if: ${{ startsWith(github.ref_name, 'release/') || startsWith(github.ref_name, 'hotfix/') }}
    uses: ./.github/workflows/GetCommitFromTag.yml
    needs: GetLatestTag
    with:
      tag: ${{ needs.GetLatestTag.outputs.tag }}

  BuildAndDeployToStg:
    if: ${{ startsWith(github.ref_name, 'release/') || startsWith(github.ref_name, 'hotfix/') }}
    needs: GetCommitFromTag
    uses: ./.github/workflows/Deploy.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STG }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STG }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY_STG }}
    with:
      region: ${{ inputs.region }}
      commit: ${{ needs.GetCommitFromTag.outputs.commit }}
      environment: STG

  NotifyToSlackToSuccess:
    if: ${{ success() }}
    needs: [GetLatestTag, GetCommitFromTag, BuildAndDeployToStg]
    uses: ./.github/workflows/NotifyToSlack.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      environment: STG
      version: ${{ needs.GetLatestTag.outputs.tag }}
      status: success
      region: ${{ inputs.region }}
      commit: ${{ needs.GetCommitFromTag.outputs.commit }}

  NotifyToSlackToFail:
    if: ${{ failure() }}
    needs: [GetLatestTag, GetCommitFromTag, BuildAndDeployToStg]
    uses: ./.github/workflows/NotifyToSlack.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      environment: STG
      version: ${{ needs.GetLatestTag.outputs.tag }}
      status: failure
      region: ${{ inputs.region }}
      commit: ${{ needs.GetCommitFromTag.outputs.commit }}