name: ManualDeployToProd

# Main 브랜치에서 가장 최근의 TAG로 AWS 배포 하는 Workflow

env:
  environment: PROD

on:
  workflow_dispatch:
    inputs:
      region:
        type: choice
        required: true
        description: 배포할 AWS region를 선택하세요.
        options:
          - eu-west-1
          - ap-northeast-2

jobs:
  # Main 브랜치에서 가장 최근의 TAG를 가져온다
  GetLatestTag:
    if: ${{ github.ref_name == 'main' }}
    uses: ./.github/workflows/GetLatestTag.yml
    with:
      environment: ${{ env.environment }}

  # tag이름으로 배포할 commit 확인
  GetCommitFromTag:
    if: ${{ github.ref_name == 'main' }}
    uses: ./.github/workflows/GetCommitFromTag.yml
    needs: GetLatestTag
    with:
      tag: ${{ needs.GetLatestTag.outputs.tag }}

  # 배포 시 필요한 값 가져오기
  GetAwsValue:
    uses: ./.github/workflows/GetAwsValue.yml
    with:
      environment: ${{ env.environment }}
      region: ${{ inputs.region }}

  # commit id로 PROD 배포
  BuildAndDeployToProd:
    if: ${{ github.ref_name == 'main' }}
    needs: [GetCommitFromTag, GetAwsValue]
    uses: ./.github/workflows/Deploy.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID_PROD }}
    with:
      region: ${{ inputs.region }}
      commit: ${{ needs.GetCommitFromTag.outputs.commit }}
      registry: ${{ needs.GetAwsValue.outputs.registry }}
      repository: ${{ needs.GetAwsValue.outputs.repository }}
      taskDefinition: ${{ needs.GetAwsValue.outputs.taskDefinition }}
      container: ${{ needs.GetAwsValue.outputs.container }}
      service: ${{ needs.GetAwsValue.outputs.service }}
      cluster: ${{ needs.GetAwsValue.outputs.cluster }}

  NotifyToSlackToSuccess:
    if: ${{ success() }}
    needs: [GetLatestTag, GetCommitFromTag, BuildAndDeployToProd]
    uses: ./.github/workflows/NotifyToSlack.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      environment: ${{ env.environment }}
      version: ${{ needs.GetLatestTag.outputs.tag }}
      status: success
      region: ${{ inputs.region }}
      commit: ${{ needs.GetCommitFromTag.outputs.commit }}

  NotifyToSlackToFail:
    if: ${{ failure() }}
    needs: [GetLatestTag, GetCommitFromTag, BuildAndDeployToProd]
    uses: ./.github/workflows/NotifyToSlack.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      environment: ${{ env.environment }}
      version: ${{ needs.GetLatestTag.outputs.tag }}
      status: failure
      region: ${{ inputs.region }}
      commit: ${{ needs.GetCommitFromTag.outputs.commit }}
