name: ManualDeployToProd
on:
  workflow_dispatch:

# Reusable workflow에서 env를 공유할 수 없음
# PROD 서버 설정 후 변경
env:
  service_prefix: ecss-an2-d-ggq
  cluster: ecsc-an2-d-ggq
  container: lol_auth

jobs:
  BuildAndDeployToProdAtReleaseBranch:
    if: ${{ startsWith(github.ref_name, 'release/') }}
    uses: ./.github/workflows/ManualDeploy.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY_PROD }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_PROD }}
    with:
      taskDefinition: task-definition-prod.json
      # Reusable workflow에서 env를 공유할 수 없음
      # TODO: STG 서버 설정 후 변경 예정
      container: lol_auth
      cluster: ecsc-an2-d-ggq
      service_prefix: ecss-an2-d-ggq

  BuildAndDeployToProdAtHotfixBranch:
    if: ${{ startsWith(github.ref_name, 'hotfix/') }}
    uses: ./.github/workflows/ManualDeploy.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY_PROD }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_PROD }}
    with:
      taskDefinition: task-definition-prod.json
      # Reusable workflow에서 env를 공유할 수 없음
      # TODO: STG 서버 설정 후 변경 예정
      container: lol_auth
      cluster: ecsc-an2-d-ggq
      service_prefix: ecss-an2-d-ggq

  TagAndMergeForProd:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    needs: [BuildAndDeployToProdAtReleaseBranch, BuildAndDeployToProdAtHotfixBranch]
    uses: ./.github/workflows/TagAndMergeToMain.yml

  NotifySlack:
    if: ${{ always() }}
    needs: TagAndMergeForProd
    uses: ./.github/workflows/NotifySlack.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      environment: "PROD"
      version: "1.0.0+123456"