name: ManualDeployToPrd
on:
  workflow_dispatch:

jobs:
  BuildAndDeployToPrd:
    if: ${{ startsWith(github.ref_name, 'release/') || startsWith(github.ref_name, 'hotfix/') }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 버전 정보 추출
        run: |
          echo "::set-output name=version::$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\+[0-9]{6}')"
        id: extract_version_name
      - name: Print Tag
        run: |
          echo ${{ steps.extract_version_name.outputs.version }}
      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.extract_version_name.outputs.version }}

      - name: Set Git config
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "Github Actions"

      - name: Merge to main
        run: |
            git fetch --unshallow
            git checkout main
            git pull
            git merge --no-ff ${{ github.ref_name }} -m "Auto-merge from ${{ github.ref_name }} to master"
            git push

      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branches: ${{ github.ref_name }}
