name: ManualDeployToStg
on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: STG
        required: true
      identifier:
        type: string
        required: false

jobs:
  BuildAndDeployToStg:
    if: ${{ inputs.environment }} == 'STG' && (startsWith(github.ref_name, 'release/') || startsWith(github.ref_name, 'hotfix/'))

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 버전 정보 추출
        run: |
          if [[ ${{ inputs.identifier }} != '' ]]; then
            echo "##[set-output name=version;]$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"-${{ inputs.identifier }}$(echo '${{ github.ref_name }}' | egrep -o '\+[0-9]{6}')
          else
            echo "##[set-output name=version;]$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')$(echo '${{ github.ref_name }}' | egrep -o '\+[0-9]{6}')"
          fi
        id: extract_version_name
      - name: Print Tag
        run: |
          echo ${{ steps.extract_version_name.outputs.version }}
      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.extract_version_name.outputs.version }}
