name: RemoveFeatureBranch

on:
  pull_request:
    types:
      - closed

jobs:
  RemoveFeatureBranch:    
    runs-on: ubuntu-latest

    steps:
      - name: trigger_event_type
        env: 
          GITHUB_EVENT: ${{ toJson(github.event.pull_request)}} 
        run: echo $GITHUB_EVENT ${{ github.ref_name }}
