name: RemoveFeatureBranch

on:
  pull_request:
    types:
      - closed
    branches: 
      - feature/**

jobs:
  build:
    if: ${{ startsWith(github.ref_name, 'feature/') && github.event.pull_request.merged }}
    
    runs-on: ubuntu-latest

    steps:
      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branches: ${{ github.ref_name }}
