name: ReportIssue

#on:
#  schedule:
#    - cron: 0 * * * *

on:
  workflow_dispatch:

jobs:
  ReportIssue:
    runs-on: ubuntu-latest
    steps:
      - name: Send Issue Result
        id: get_issue
        uses: ggqcompany/github-actions-slack@v1
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        with:
          status: report-issue
          fields: all

      - name: Print
        run: |
          echo ISSUES = ${{ steps.get_issue.outputs.issues }}
