name: ReportIssue

#on:
#  schedule:
#    - cron: 0 * * * *

on:
  workflow_dispatch:

jobs:
  ReportIssue:
    runs-on: ubuntu-latest
    steps:
      - name: Send Issue Result
        uses: KyeongminKang-GGQ/action-slack@v2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        with:
          status: report-issue
          fields: all
