name: RollbackDeploy
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: 배포할 tag 이름을 입력하세요.

jobs:
  GetCommitFromTag:
    if: ${{ inputs.tag != '' }}
    uses: ./.github/workflows/GetCommitFromTag.yml
    needs: GetLatestTag
    with:
      tag: ${{ inputs.tag }}

  RollbackDeploy:
    if: ${{ needs.GetCommitFromTag.outputs.commit != '' }}
    needs: GetCommitFromTag
    uses: ./.github/workflows/Deploy.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY_PROD }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_PROD }}
    with:
      taskDefinition: task-definition-prod.json
      # Reusable workflow에서 env를 공유할 수 없음
      container: lol_auth
      cluster: ecsc-an2-d-ggq
      service_prefix: ecss-an2-d-ggq
      region: ${{ inputs.region }}
      commit: ${{ needs.GetCommitFromTag.outputs.commit }}

  NotifyToSlackToSuccess:
    if: ${{ success() }}
    needs: [GetCommitFromTag, RollbackDeploy]
    uses: ./.github/workflows/NotifyToSlack.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      environment: PROD
      version: ${{ inputs.tag }}
      status: success
      region: ${{ inputs.region }}
      commit: ${{ needs.GetCommitFromTag.outputs.commit }}

  NotifyToSlackToFail:
    if: ${{ failure() }}
    needs: [GetCommitFromTag, RollbackDeploy]
    uses: ./.github/workflows/NotifyToSlack.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      environment: PROD
      version: ${{ inputs.tag }}
      status: failure
      region: ${{ inputs.region }}
      commit: ${{ needs.GetCommitFromTag.outputs.commit }}