name: SetTag
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 배포 환경
        options:
          - STG
          - PROD

jobs:
  GetLatestTag:
    uses: ./.github/workflows/GetLatestTag.yml

  # release/hotfix 브랜치에서 RC버전 태깅
  ExtractNewTagForStg:
    if: ${{ inputs.environment == 'STG' && (startsWith(github.ref_name, 'release/') || startsWith(github.ref_name, 'hotfix/')) }}
    needs: GetLatestTag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.extract_new_tag.outputs.tag }}
    steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Print values
          run: |
            echo environment = ${{ inputs.environment }} / branch = ${{ github.ref_name }} / current_tag = ${{ needs.GetLatestTag.outputs.tag }}

        - if: ${{ needs.GetLatestTag.outputs.tag != '' }}
          name: Get latest RC tag
          id: extract_rc_version
          run: |
            if '${{ startsWith(github.ref_name, 'hotfix/') }}'
            then
              echo "::set-output name=version::$(echo ${{ needs.GetLatestTag.outputs.tag }}) | sed -rn 's/[[:digit:]]{1,3}.[[:digit:]]{1,3}.[[:digit:]]{1,3}-rc.([[:digit:]]*)\+hotfix.[[:digit:]]{6}/\1/p'"
            else
              echo "::set-output name=version::$(echo ${{ needs.GetLatestTag.outputs.tag }}) | sed -rn 's/[[:digit:]]{1,3}.[[:digit:]]{1,3}.[[:digit:]]{1,3}-rc.([[:digit:]]*)\+[[:digit:]]{6}/\1/p'"
            fi

        - if: ${{ needs.GetLatestTag.outputs.tag != '' }}
          name: Print latest RC tag
          run: |
            echo ${{ steps.extract_rc_version.outputs.version }}

        - if: ${{ needs.GetLatestTag.outputs.tag != '' }}
          name: Calculate new RC tag
          id: extract_new_rc_version
          run: |
            if '${{ steps.extract_rc_version.outputs.version != '' }}'
            then
              echo "::set-output name=version::$(($(echo ${{ steps.extract_rc_version.outputs.version }}) + 1))"
            else
              echo "::set-output name=version::$(echo ${{ steps.extract_rc_version.outputs.version }})"
            fi

        - name: Print new tag
          id: extract_new_tag
          run: |
            if '${{ inputs.environment == 'STG' && steps.extract_new_rc_version.outputs.version != '' }}'
            then
              if '${{ startsWith(github.ref_name, 'hotfix/') }}'
              then
                echo "::set-output name=tag::$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')-rc.${{ steps.extract_new_rc_version.outputs.version }}+hotfix.$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{6}')"
              elif '${{ startsWith(github.ref_name, 'release/') }}'
              then
                echo "::set-output name=tag::$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')-rc.${{ steps.extract_new_rc_version.outputs.version }}$(echo '${{ github.ref_name }}' | egrep -o '\+[0-9]{6}')"
              else
                echo ""
              fi
            elif '${{ inputs.environment == 'PROD' }}'
            then
              if '${{ startsWith(github.ref_name, 'hotfix/') }}'
              then
                echo "::set-output name=tag::$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')+hotfix.$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{6}')"
              elif '${{ startsWith(github.ref_name, 'release/') }}'
              then
                echo "::set-output name=tag::$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\+[0-9]{6}')"
              else
                echo ""
              fi
            else
              echo ""
            fi

        - if: ${{ steps.extract_new_tag.outputs.tag != '' }}
          name: Print tag name
          run: |
            echo ${{ steps.extract_new_tag.outputs.tag }}

  SetTagForStg:
    if: ${{ needs.ExtractVersion.outputs.tag != '' }}
    uses: ./.github/workflows/SetTagForStg.yml
    needs: ExtractNewTagForStg
    with:
      version: ${{ needs.ExtractVersion.outputs.tag }}

  SetTagForProd:
    uses: ./.github/workflows/SetTagForProd.yml
    with:
      environment: ${{ inputs.environment }}
