name: SetTagForStg

on:
  workflow_dispatch:

jobs:
  GetLatestRcTag:
    if: ${{ startsWith(github.ref_name, 'release/') || startsWith(github.ref_name, 'hotfix/') }}
    uses: ./.github/workflows/GetLatestTag.yml
    with:
      environment: STG

  # release/hotfix 브랜치에서 RC버전 태깅
  MakeNewTagForStg:
    if: ${{ startsWith(github.ref_name, 'release/') || startsWith(github.ref_name, 'hotfix/') }}
    needs: GetLatestRcTag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.extract_new_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Print values
        run: |
          echo branch = ${{ github.ref_name }} / current_tag = ${{ needs.GetLatestRcTag.outputs.tag }}

      - if: ${{ needs.GetLatestRcTag.outputs.tag != '' }}
        name: Get latest RC tag
        id: extract_rc_version
        run: |
          if '${{ startsWith(github.ref_name, 'hotfix/') }}'
          then
            echo "::set-output name=version::$(echo ${{ needs.GetLatestRcTag.outputs.tag }}) | sed -rn 's/[[:digit:]]{1,3}.[[:digit:]]{1,3}.[[:digit:]]{1,3}-rc.([[:digit:]]*)\+hotfix.[[:digit:]]{6}/\1/p'"
          else
            echo "::set-output name=version::$(echo ${{ needs.GetLatestRcTag.outputs.tag }}) | sed -rn 's/[[:digit:]]{1,3}.[[:digit:]]{1,3}.[[:digit:]]{1,3}-rc.([[:digit:]]*)\+[[:digit:]]{6}/\1/p'"
          fi

      - if: ${{ needs.GetLatestRcTag.outputs.tag != '' }}
        name: Print latest RC tag
        run: |
          echo ${{ steps.extract_rc_version.outputs.version }}

      - name: Calculate new RC tag
        id: extract_new_rc_version
        run: |
          if '${{ steps.extract_rc_version.outputs.version != '' }}'
          then
            echo "::set-output name=version::$(($(echo ${{ steps.extract_rc_version.outputs.version }}) + 1))"
          else
            echo "::set-output name=version::1"
          fi

      - if: ${{ steps.extract_new_rc_version.outputs.version != '' }}
        name: Print new tag
        id: extract_new_tag
        run: |
          if '${{ startsWith(github.ref_name, 'hotfix/') }}'
          then
            echo "::set-output name=tag::$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')-rc.${{ steps.extract_new_rc_version.outputs.version }}+hotfix.$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{6}')"
          elif '${{ startsWith(github.ref_name, 'release/') }}'
          then
            echo "::set-output name=tag::$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')-rc.${{ steps.extract_new_rc_version.outputs.version }}$(echo '${{ github.ref_name }}' | egrep -o '\+[0-9]{6}')"
          else
            echo ""
          fi

      - if: ${{ steps.extract_new_tag.outputs.tag != '' }}
        name: Print tag name
        run: |
          echo ${{ steps.extract_new_tag.outputs.tag }}

  SetTagForStg:
    if: ${{ startsWith(github.ref_name, 'release/') || startsWith(github.ref_name, 'hotfix/') }}
    needs: MakeNewTagForStg
    runs-on: ubuntu-latest
    steps:
      - if: ${{ needs.MakeNewTagForStg.outputs.tag != '' }}
        name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.MakeNewTagForStg.outputs.tag }}
