name: SetTag
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 배포 환경
        options:
          - STG
          - PRD

jobs:
  ExtractRcVersion:
    if: ${{ inputs.environment == 'STG' && (startsWith(github.ref_name, 'release/') || startsWith(github.ref_name, 'hotfix/')) }}
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Get tag
          id: extract_rc_version
          run: |
            echo "::set-output name=version::$(git describe --tag --abbrev=0) | sed -rn 's/[[:digit:]]{1,3}.[[:digit:]]{1,3}.[[:digit:]]{1,3}-rc.([[:digit:]]*)\+[[:digit:]]{6}/\1/p'"

        - name: Print RC Version
          run: |
            echo ${{ steps.extract_rc_version.outputs.version }}
            echo $(($(echo ${{ steps.extract_rc_version.outputs.version }}) + 1))

        - name: Print Tag Version
          id: extract_tag_version
          run: |
            if '${{ steps.extract_rc_version.outputs.version != '' }}'
            then
              echo "::set-output name=tagVersion::$(($(echo ${{ steps.extract_rc_version.outputs.version }}) + 1))"
            else
              echo "::set-output name=tagVersion::$(echo ${{ steps.extract_rc_version.outputs.version }})"
            fi

        - name: Print TAG Version
          run: |
            echo ${{ steps.extract_tag_version.outputs.tagVersion }}
