name: SetTag
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 배포 환경
        options:
          - STG
          - PRD

jobs:
  ExtractRcVersion:
    if: ${{ inputs.environment == 'STG' && (startsWith(github.ref_name, 'release/') || startsWith(github.ref_name, 'hotfix/')) }}
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: olegtarasov/get-tag@v2.1
          id: tagName
          with:
            tagRegex: "\d{1,3}.\d{1,3}.\d{1,3}-rc.(\d+)\+\d{6}"  # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
            tagRegexGroup: 1 # Optional. Default is 1.

        - name: Show tag name
          run: |
            echo ${{ steps.tagName.outputs.tag }}
