name: SetTagForStg

on:
  workflow_call:
    outputs:
      version:
        description: "Extract version name"
        value: ${{ jobs.SetTagForStg.outputs.version }}
    inputs:
      identifier:
        type: string
        required: false

jobs:
  SetTagForStg:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version_name.outputs.version }}
    steps:
      - name: Start SetTagForStg Workflow
        run: |
          echo Start SetTagForStg Workflow

      - uses: actions/checkout@v2
      - name: Extract Version Name
        run: |
          if '${{ startsWith(github.ref_name, 'hotfix/') }}'
          then
            echo "::set-output name=version::$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')-${{ inputs.identifier }}$(echo '${{ github.ref_name }}' | egrep -o '\+[0-9]{6}')"
          elif '${{ startsWith(github.ref_name, 'release/') }}'
          then
            echo "::set-output name=version::$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')-${{ inputs.identifier }}$(echo '${{ github.ref_name }}' | egrep -o '\+[0-9]{6}')"
          else
            echo ""
          fi
        id: extract_version_name

      - name: Print Tag
        run: |
          echo ${{ steps.extract_version_name.outputs.version }}

      - if: ${{ steps.extract_version_name.outputs.version != '' }}
        name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.extract_version_name.outputs.version }}
