name: TagAndMergeToMain

on:
  workflow_call:

jobs:
  ManualDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: 버전 정보 추출
        run: |
          if '${{ startsWith(github.ref_name, 'hotfix/') }}'
          then
            echo "::set-output name=version::$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')+hotfix.$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{6}')"
          elif '${{ startsWith(github.ref_name, 'release/') }}'
          then
            echo "::set-output name=version::$(echo '${{ github.ref_name }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\+[0-9]{6}')"
          else
            echo ""
        id: version

      - if: ${{ inputs.version != '' }}
        name: Print Tag
        run: |
          echo ${{ inputs.version }}

      - if: ${{ inputs.version != '' }}
        name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

      - if: ${{ inputs.version != '' }}
        name: Merge to main
        run: |
          git fetch --unshallow
          git checkout main
          git pull
          git merge --no-ff ${{ github.ref_name }} -m "Auto-merge from ${{ github.ref_name }} to main"
          git push
          git tag ${{ inputs.version }}
          git push origin ${{ inputs.version }}

      - if: ${{ inputs.version != '' }}
        name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.version }}
          release_name: ${{ inputs.version }}

      - if: ${{ inputs.version != '' }}
        name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: ${{ github.ref_name }}
