name: Create issues from todos

on:
  push:
    branches:
      - develop

jobs:
  CheckTodoComments:
    outputs:
      OPENED_ISSUE: ${{ env.OPENED_ISSUE }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: todo-actions
        uses: dtinth/todo-actions@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TODO_ACTIONS_MONGO_URL: ${{ secrets.TODO_ACTIONS_MONGO_URL }}

      - name: Find issues
        id: find-issues
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'find-issues'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-state: 'open'

      - name: Print issues
        run: |
            echo ${{ steps.find-issues.outputs.issues }} | jq '. | length
            echo "OPENED_ISSUE=$(echo ${{ steps.find-issues.outputs.issues }} | jq '. | length)" >> $GITHUB_ENV

      - name: Print env
        run: |
          echo OPENED_ISSUE = ${{ env.OPENED_ISSUE }}
          if '${{ env.OPENED_ISSUE > 0 }}'
          then
            core.setFailed('Unresolved issue ${{ env.OPENED_ISSUE }}')
          fi

  NotifyToSlackToFail:
    if: ${{ failure() }}
    needs: [CheckTodoComments]
    uses: ./.github/workflows/NotifyToSlack.yml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      version: 1.0.0
      status: failure
      region: ap-northeast
      commit: commit
      additionalInfo: Unresolved issue - ${{ needs.CheckTodoComments.outputs.OPENED_ISSUE }}
