name: Create issues from todos

on:
  push:
    branches:
      - develop

jobs:
  todos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: todo-actions
        uses: dtinth/todo-actions@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}